### ISSUE TITLE
does not invoke Accounts.onLogin on the server side

### ISSUE THREAD

**Issue by natb1** [xolvio/meteor-twitter-stub#1]
This does not appear to invoke Accounts.onLogin on the server side. Is this the expected/desired behavior?

(btw this is a great code example thanks)

**Comment by SamHatoum** [comment]
Hey

I doubt that has anything to do with this stub. Are you using any spies anywhere else? Perhaps try to isolate the issue by using a clean repo with real twitter login then this stub and seeing if the issue happens.

I could be wrong!

Sam

**Comment by natb1** [comment]
right you are, thank you. sorry for the false alarm

**Comment by SamHatoum** [comment]
you're welcome!
